/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_paulbutcher_scalakey_Mesh */

#ifndef _Included_com_paulbutcher_scalakey_Mesh
#define _Included_com_paulbutcher_scalakey_Mesh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_paulbutcher_scalakey_Mesh
 * Method:    initializeBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_paulbutcher_scalakey_Mesh_initializeBuffers
  (JNIEnv *, jobject);

/*
 * Class:     com_paulbutcher_scalakey_Mesh
 * Method:    ripple
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_paulbutcher_scalakey_Mesh_ripple
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
